# version: 2.1

# orbs:
#   php: circleci/php@1.1.0

# jobs:
#   install_dependencies:
#     docker:
#       - image: cimg/php:7.4 
#     steps:
#       - checkout
#       - php/install-composer:
#           install-version: 2.0.8 
#       - php/install-packages

#   run_tests:
#     docker:
#       - image: cimg/php:7.4
#     steps:
#       - php/install-composer:
#           install-version: 2.0.8
#       - php/install-packages
#       - run:
#           name: Run Test Cases
#           command: composer test

# workflows:
#   test_application:
#     jobs:
#       - install_dependencies
#       - run_tests


#-----------------------------------------------------------

# version: 2.1

# orbs:
#   php: circleci/php@1.1.0

# jobs:

#   run_tests:
#     docker:
#       - image: cimg/php:7.4
#     steps:
#       - php/install-composer:
#           install-version: 2.0.8
#       - php/install-packages
#       - run:
#           name: Run Test Cases
#           command: composer test

# workflows:
#   test_application:
#     jobs:
#       - run_tests

#------------------------------------------------------------------

# version: 2.1

# orbs:
#   php: circleci/php@1.1.0

# jobs:

#   run_tests:
#     docker:
#       - image: cimg/php:7.4
#     working_directory: /home/circleci/project  # Set the correct working directory
#     steps:
#       - checkout  # This will clone your repository into the working directory
#       - php/install-composer:
#           install-version: 2.0.8
#       - php/install-packages
#       - run:
#           name: Run Test Cases
#           command: phpunit --testsuite=Unit 

# workflows:
#   test_application:
#     jobs:
#       - run_tests

#------------------------------------------------------
version: 2.1

orbs:
  phpunit: stockfiller/phpunit@1.0.0
  php: circleci/php@1.1.0  # Still using this for Composer if necessary

jobs:
  run_tests:
    docker:
      - image: cimg/php:7.4  # Use the appropriate PHP image version
    working_directory: ~/project  # Set the correct working directory
    steps:
      - checkout  # Checkout the code from the repository

      # Install Composer using the CircleCI PHP orb
      - php/install-composer:
          install-version: 2.0.8

      # Install project dependencies
      - run:
          name: Install Dependencies
          command: composer install --no-interaction --no-progress --no-suggest

      # Use the PHPUnit Orb to run tests
      - phpunit/run:
          tests: "tests"  # Directory containing your tests
          phpunit_version: "9.5.0"  # Specify a version if needed
          options: "--testsuite=Unit"  # Custom options for PHPUnit

workflows:
  test_application:
    jobs:
      - run_tests
